Scipy structure refinement
pep-dortmund/toolbox-workshop pull request #228
Opened 2020-09-02 20:07 UTC by karl9000

The content is not changed too much. In total, a section-based structure is introduced and a bit more descriptive text is added.

2020-09-04 17:56 UTC, chrbeckm commented on python/scientific-python.ipynb
> +    "- Lineare und Nichtlineare Regression"
In the python-notebook, we use a table of content.
Use 
```
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')
```
in a Code cell and
```
# Inhalt

<div id="toc"></div>
```
in a Markdown cell.

2020-09-04 17:57 UTC, chrbeckm commented on python/scientific-python.ipynb
> -    "import numpy as np\n",
Numpy is needed later on!

2020-09-04 18:00 UTC, chrbeckm commented on python/scientific-python.ipynb
> +    "from scipy.stats import gmean, sem\n",
`gmean` is unused

2020-10-08 16:00 UTC, dormail requested changes
Need to add stuff to lecture frame "What is Unix?"

2020-10-08 16:08 UTC, maxnoe commented
Why include unix stuff at all in a PR about scipy. Please just open another one and remove the changes here.

2020-10-09 08:11 UTC, maxnoe approved these changes

2020-10-09 08:14 UTC, maxnoe approved these changes
Thanks! I just added the javascript call to actually fill the toc

2020-10-09 08:15 UTC, merged