2020 template babel
pep-dortmund/toolbox-workshop pull request #233
Opened 2020-10-05 13:01 UTC by chrbeckm

2020-10-05 13:03 UTC, MaxNoe requested changes

2020-10-05 13:03 UTC, MaxNoe commented on latex-template/header.tex
> +\usepackage[ngerman]{babel}
Warum wurde das geändert? Das ist wichtig sobald man mehr als eine Sprache braucht und ich würde sagen best practice das main immer anzugeben

2020-10-05 13:04 UTC, MaxNoe commented
In meinem aktuellen TL 2020 funktioniert das auch.

2020-10-05 13:19 UTC, chrbeckm commented
```
Package biblatex Warning: Language 'nil' not supported.
(biblatex)                Using dummy definitions on input line 11.


! Package etoolbox Error: Toggle 'blx@lang@captions@english' undefined.

See the etoolbox package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.11 \begin{document}

```

Das ist meine Fehlermeldung ohne die Änderungen.

2020-10-05 13:22 UTC, MaxNoe commented
Ich habe gerade nochmal geupdated und das funktioniert.

2020-10-05 13:28 UTC, MaxNoe commented
Der Fehler kommt erst beim laden von biblatex.

Related: https://tex.stackexchange.com/questions/563079/recompiling-on-another-newer-imac-i-obtain-error-libroorange-tex187-packag

2020-10-06 12:41 UTC, maxnoe commented
See #234

2020-10-07 12:28 UTC, maxnoe commented
Checking the documentation again, it is recommended not to use `main` but to give the main language of the document as the last option.

Can you add a comment on that to the LaTeX slides and fix the order of the languages in `packages.tex`?

Then we can merge

2020-10-07 15:07 UTC, maxnoe approved these changes

2020-10-07 15:08 UTC, merged

2020-10-07 15:08 UTC, maxnoe commented
nice, thanks!