update scipy notebook
pep-dortmund/toolbox-workshop pull request #368
Opened 2023-09-27 15:25 UTC by chrbeckm

Closes #363

2023-09-28 08:19 UTC, aknierim approved these changes

2023-09-29 05:05 UTC, jpherdi requested changes

2023-09-29 05:05 UTC, jpherdi commented on python/scientific-python.ipynb
> +    "planck2 = const.physical_constants[\"Planck constant\"]  # returns value, unit and uncertainty\n",
Give better name, e.g. planck_full

2023-09-29 05:05 UTC, jpherdi commented on python/scientific-python.ipynb
> +    "print(f\"{planck = }\", f\"{planck2 = }\", sep=\"\\n\")"
Change here correspondingly

2023-09-29 05:07 UTC, jpherdi commented
Also add the other points regarding plots mentioned by @aknierim in his issue

2023-09-29 07:16 UTC, jpherdi approved these changes

2023-09-29 07:22 UTC, merged