start cheat-sheet as help during exercises
pep-dortmund/toolbox-workshop pull request #369
Opened 2023-09-28 11:10 UTC by SepplL

any important addition?

2023-09-28 11:11 UTC, maxnoe commented on terminal-cheat-sheet/content/cheat-sheet.tex
> +    mamba activate toolbox & laedt die installierten \texttt{python} Pakete \\
lädt

2023-09-28 11:18 UTC, aknierim commented
I would add `cd -` to get back to the last directory you came from

2023-09-28 11:33 UTC, maxnoe commented
Maybe add a code example or screenshot how the Terminal looks like and how the ipython prompt looks like?

2023-09-28 11:35 UTC, SepplL commented
> Maybe add a code example or screenshot how the Terminal looks like and how the ipython prompt looks like?

I'd rather have it as one compact slide on the wall during the exercises with not too much going on.
So no scrolling and no confusion with too much information and more as a 'look up' on the fly while the students try out things.

2023-09-29 05:30 UTC, jpherdi requested changes

2023-09-29 05:30 UTC, jpherdi commented on terminal-cheat-sheet/content/cheat-sheet.tex
> +    codium . & öffnet VSCodium im aktuellen Verzeichnis \\
```suggestion
    codium . & öffnet VSCodium im aktuellen Verzeichnis (Mac/Linux) \\
```

2023-09-29 05:30 UTC, jpherdi commented on terminal-cheat-sheet/README.md
> +In diesem Slide findet sich eine uebersicht der wichtigen Terminal Befehle wieder.
```suggestion
Diese Folie zeigt eine Übersicht der wichtigsten Terminalbefehle für die ersten Tage vor dem Unix-Vortrag.
```

2023-09-29 05:30 UTC, jpherdi commented on terminal-cheat-sheet/content/cheat-sheet.tex
> +    cd <dirname> & \enquote{change directory} wechselt in den angegebenen \\
```suggestion
    cd <dirname> & \enquote{change directory} wechselt in das Verzeichnis <dirname> \\
```

2023-09-29 05:30 UTC, jpherdi commented on terminal-cheat-sheet/content/cheat-sheet.tex
> +    cd <dirname> & \enquote{change directory} wechselt in den angegebenen \\
Würde ich als erstes schreiben und dann `cd ..` und `cd -` als Spezialfälle zeigen

2023-09-29 05:30 UTC, jpherdi commented on terminal-cheat-sheet/content/cheat-sheet.tex
> +    cd .. & \enquote{change directory} wechselt in den Oberordner \\
```suggestion
    cd .. & wechselt in das Oberverzeichnis \\
```

2023-09-29 05:30 UTC, jpherdi commented on terminal-cheat-sheet/content/cheat-sheet.tex
> +    cd - & \enquote{change directory} in das vorherige Verzeichnis \\
```suggestion
    cd - & wechselt in das vorherige Verzeichnis \\
```

2023-09-29 16:01 UTC, merged